version: '2'
services:
  consul:
    extends:
      file: base.yml
      service: base
    image: qnib/alpn-consul
    hostname: nifi-consul
    container_name: nifi-consul
    ports:
     - 8500:8500
    environment:
     - CONSUL_BOOTSTRAP=true

  zkui:
    extends:
      file: base.yml
      service: client
    hostname: nifi-zkui
    container_name: nifi-zkui
    image: qnib/zkui
    ports:
     - 9090:9090

  zookeeper:
    extends:
      file: base.yml
      service: client
    hostname: nifi-zookeeper
    container_name: nifi-zookeeper
    image: qnib/zookeeper
    ports:
     - 2181:2181

  elasticsearch:
    hostname: elasticsearch
    container_name: elasticsearch
    extends:
      file: base.yml
      service: elasticsearch

  kopf:
    extends:
      file: base.yml
      service: kopf

  nifi:
    extends:
      file: base.yml
      service: client
    image: qnib/nifi
    hostname: nifi
    container_name: nifi
    ports:
     - 8080:8080
    
networks:
  nifi-net:
    driver: bridge
